アンケートフォーム
w-shaulabg/enquete pull request #2
Opened 2022-10-11 12:37 UTC by w-shaulabg

お疲れ様です！
アンケートフォームを提出いたします！
お手隙の際にご確認のほどよろしくお願いいたします！

<img width="505" alt="スクリーンショット 2022-10-11 21 28 14" src="https://user-images.githubusercontent.com/100771427/195091446-fa70481d-18c4-4e16-95cd-9d3d78134412.png">
<img width="387" alt="スクリーンショット 2022-10-11 21 29 51" src="https://user-images.githubusercontent.com/100771427/195091518-58d8290c-4cfd-4091-ae2e-3abd9e233cfa.png">
<img width="559" alt="スクリーンショット 2022-10-11 21 30 05" src="https://user-images.githubusercontent.com/100771427/195091555-d2dba97f-7203-4da6-a02c-765cdd175f59.png">
<img width="1180" alt="スクリーンショット 2022-10-11 21 28 46" src="https://user-images.githubusercontent.com/100771427/195091592-b00b9a71-d80e-4a52-bbcf-aaabb0d69885.png">

2022-10-12 16:25 UTC, KatsuyaTanaka95 approved these changes
デザインも綺麗ですね！！
レビューさせていただきましたので、ご確認をよろしくです！！！🙆😊

2022-10-12 16:25 UTC, KatsuyaTanaka95 commented on src/public/complete.php
> +  $res = $stmt->execute();
$resはなくても問題なく動いたりしますでしょうか？？
もし、動くようであれば削除しちゃいましょう！！！😊

2022-11-21 06:42 UTC, KatsuyaTanaka95 requested changes
確認してみてください！😊

2022-11-21 06:42 UTC, KatsuyaTanaka95 commented on src/public/complete.php
> -  $res = $stmt->execute();
> $stmt->execute();

こちらはなくさなくて良い気がします！
「$res =」 の箇所がいらないのかなと思ってました！
確認してみていただけると助かります^ ^

2022-11-29 00:46 UTC, gotokouichi approved these changes
LGTMです！✨
ご自身でマージしちゃってください！😊

2022-12-12 11:20 UTC, merged